#import <Foundation/Foundation.h>

// ! Project version number
FOUNDATION_EXPORT double opencv2VersionNumber;

// ! Project version string
FOUNDATION_EXPORT const unsigned char opencv2VersionString[];

#import <opencv2/MatOfRect2d.h>
#import <opencv2/MatOfFloat4.h>
#import <opencv2/MatOfPoint2i.h>
#import <opencv2/Double3.h>
#import <opencv2/MatOfByte.h>
#import <opencv2/Range.h>
#import <opencv2/Size2f.h>
#import <opencv2/Converters.h>
#import <opencv2/Mat.h>
#import <opencv2/ByteVector.h>
#import <opencv2/Point2f.h>
#import <opencv2/KeyPoint.h>
#import <opencv2/Rect2f.h>
#import <opencv2/Float6.h>
#import <opencv2/MatOfKeyPoint.h>
#import <opencv2/MatOfRect2i.h>
#import <opencv2/FloatVector.h>
#import <opencv2/TermCriteria.h>
#import <opencv2/Int4.h>
#import <opencv2/MatOfDMatch.h>
#import <opencv2/Scalar.h>
#import <opencv2/Point3f.h>
#import <opencv2/MatOfDouble.h>
#import <opencv2/IntVector.h>
#import <opencv2/RotatedRect.h>
#import <opencv2/MatOfFloat6.h>
#import <opencv2/DoubleVector.h>
#import <opencv2/Size2d.h>
#import <opencv2/MinMaxLocResult.h>
#import <opencv2/MatOfInt4.h>
#import <opencv2/Rect2i.h>
#import <opencv2/Point2i.h>
#import <opencv2/MatOfPoint3.h>
#import <opencv2/MatOfRotatedRect.h>
#import <opencv2/DMatch.h>
#import <opencv2/Point3i.h>
#import <opencv2/CvType.h>
#import <opencv2/CVObjcUtil.h>
#import <opencv2/Size2i.h>
#import <opencv2/Float4.h>
#import <opencv2/MatOfFloat.h>
#import <opencv2/Rect2d.h>
#import <opencv2/MatOfPoint2f.h>
#import <opencv2/Point2d.h>
#import <opencv2/Double2.h>
#import <opencv2/MatOfInt.h>
#import <opencv2/ArrayUtil.h>
#import <opencv2/MatOfPoint3f.h>
#import <opencv2/Point3d.h>
#import <opencv2/Core.h>
#import <opencv2/Algorithm.h>
#import <opencv2/TickMeter.h>
#import <opencv2/Moments.h>
#import <opencv2/Imgproc.h>
#import <opencv2/CLAHE.h>
#import <opencv2/GeneralizedHough.h>
#import <opencv2/GeneralizedHoughBallard.h>
#import <opencv2/GeneralizedHoughGuil.h>
#import <opencv2/LineSegmentDetector.h>
#import <opencv2/Subdiv2D.h>
#import <opencv2/Dnn.h>
#import <opencv2/ClassificationModel.h>
#import <opencv2/DetectionModel.h>
#import <opencv2/DictValue.h>
#import <opencv2/KeypointsModel.h>
#import <opencv2/Layer.h>
#import <opencv2/Model.h>
#import <opencv2/Net.h>
#import <opencv2/SegmentationModel.h>
#import <opencv2/TextDetectionModel.h>
#import <opencv2/TextDetectionModel_DB.h>
#import <opencv2/TextDetectionModel_EAST.h>
#import <opencv2/TextRecognitionModel.h>
#import <opencv2/Wechat_qrcode.h>
#import <opencv2/WeChatQRCode.h>